# INFOMATION
VERSION = "1.0.0"
PROJECT_NAME = "PROJECT NAME %s" % VERSION
LOG_DIR = "logs"
ABOUT = "Version %s \n-updates: " % VERSION

# WORKFLOW
STEP_WAIT_TRIGGER = "STEP_WAIT_TRIGGER"
STEP_PREPROCESS = "STEP_PREPROCESS"
STEP_PROCESSING = "STEP_PROCESSING"
STEP_OUTPUT = "STEP_OUTPUT"
STEP_RELEASE = "STEP_RELEASE"

# RESULT
RESULT_WAIT = "WAIT"
RESULT_PASS = "PASS"
RESULT_FAIL = "FAIL"

# OBJECT
ZERO_INDEX = 0
ONE_INDEX = 1
TWO_INDEX = 2


# COLOR
CV_GREEN = (0, 255, 0)
CV_BLUE = (255, 0, 0)
CV_ORANGE = (175, 0, 175)
CV_RED = (0, 0, 255)
CV_DARK_RED = (0, 0, 128)

# FORMAT
FILENAME_FORMAT = "%Y%m%d_%H%M%S.jpg"
DATETIME_FORMAT = "%Y/%m/%d %H:%M:%S"
FOLDER_DATE_FORMAT = "%Y-%m-%d"

# CONFIG
IMAGE_PATH_COLUMN = 4
FONT_CONFIG_PATH = "resources/fonts/font.json"
