# INFOMATION
VERSION = "1.0.0"
PROJECT_NAME = "PROJECT NAME %s" % VERSION
LOG_DIR = "logs"
ABOUT = "Version %s \n-updates: " % VERSION

# WORKFLOW AUTO
STEP_WAIT_TRIGGER_AUTO = "STEP_WAIT_TRIGGER_AUTO"
STEP_RELEASE_AUTO = "STEP_RELEASE_AUTO"

# WEIGHT
STEP_CHECK_WEIGHT_AUTO = "STEP_CHECK_WEIGHT_AUTO"
STEP_OUTPUT_WEIGHT_AUTO = "STEP_OUTPUT_WEIGHT_AUTO"

# OPTIC
STEP_PREPROCESS_OPTIC_AUTO = "STEP_PREPROCESS_OPTIC_AUTO"
STEP_PROCESSING_OPTIC_AUTO = "STEP_PROCESSING_OPTIC_AUTO"
STEP_OUTPUT_OPTIC_AUTO = "STEP_OUTPUT_OPTIC_AUTO"

# WORKFLOW TEACHING
STEP_WAIT_TRIGGER_TEACHING = "STEP_WAIT_TRIGGER_TEACHING"
STEP_PREPROCESS_TEACHING = "STEP_PREPROCESS_TEACHING"
STEP_PROCESSING_TEACHING = "STEP_PROCESSING_TEACHING"
STEP_OUTPUT_TEACHING = "STEP_OUTPUT_TEACHING"
STEP_RELEASE_TEACHING = "STEP_RELEASE_TEACHING"

# RESULT
RESULT_WAIT = "WAIT"
RESULT_PASS = "PASS"
RESULT_FAIL = "FAIL"

# OBJECT
ZERO_INDEX = 0
ONE_INDEX = 1
TWO_INDEX = 2


# COLOR
CV_GREEN = (0, 255, 0)
CV_BLUE = (255, 0, 0)
CV_ORANGE = (175, 0, 175)
CV_RED = (0, 0, 255)
CV_DARK_RED = (0, 0, 128)

# FORMAT
FILENAME_FORMAT = "%Y%m%d_%H%M%S.jpg"
DATETIME_FORMAT = "%Y/%m/%d %H:%M:%S"
FOLDER_DATE_FORMAT = "%Y-%m-%d"

# CONFIG
IMAGE_PATH_COLUMN = 4
FONT_CONFIG_PATH = "resources/fonts/font.json"
# LABEL_CONFIG_PATH = "resources/models_ai/labels.yaml"
LABEL_CONFIG_PATH = "resources/models_ai/labels_optic.yaml"
