# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\LoadingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLoading(object):
    def setupUi(self, DialogLoading):
        DialogLoading.setObjectName("DialogLoading")
        DialogLoading.resize(600, 400)
        DialogLoading.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogLoading)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelLoading = QtWidgets.QLabel(DialogLoading)
        self.labelLoading.setMinimumSize(QtCore.QSize(300, 200))
        self.labelLoading.setMaximumSize(QtCore.QSize(300, 200))
        self.labelLoading.setText("")
        self.labelLoading.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoading.setObjectName("labelLoading")
        self.verticalLayout.addWidget(self.labelLoading, 0, QtCore.Qt.AlignHCenter)
        self.labelMessage = QtWidgets.QLabel(DialogLoading)
        self.labelMessage.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout.addWidget(self.labelMessage)
        self.progressBar = QtWidgets.QProgressBar(DialogLoading)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(DialogLoading)
        QtCore.QMetaObject.connectSlotsByName(DialogLoading)

    def retranslateUi(self, DialogLoading):
        _translate = QtCore.QCoreApplication.translate
        DialogLoading.setWindowTitle(_translate("DialogLoading", "Đang tải..."))
        self.labelMessage.setText(_translate("DialogLoading", "Vui lòng đợi trong giây lát..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogLoading = QtWidgets.QDialog()
    ui = Ui_DialogLoading()
    ui.setupUi(DialogLoading)
    DialogLoading.show()
    sys.exit(app.exec_())
