# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\PopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PopUp(object):
    def setupUi(self, PopUp):
        PopUp.setObjectName("PopUp")
        PopUp.resize(450, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(PopUp)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_message = QtWidgets.QLabel(PopUp)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        self.mnv = QtWidgets.QHBoxLayout()
        self.mnv.setObjectName("mnv")
        self.label_mnv = QtWidgets.QLabel(PopUp)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mnv.setFont(font)
        self.label_mnv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mnv.setObjectName("label_mnv")
        self.mnv.addWidget(self.label_mnv)
        self.line_mnv = QtWidgets.QLineEdit(PopUp)
        self.line_mnv.setMinimumSize(QtCore.QSize(0, 30))
        self.line_mnv.setObjectName("line_mnv")
        self.mnv.addWidget(self.line_mnv)
        self.verticalLayout.addLayout(self.mnv)
        self.btn = QtWidgets.QHBoxLayout()
        self.btn.setObjectName("btn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btn.addItem(spacerItem)
        self.btn_fail = QtWidgets.QPushButton(PopUp)
        self.btn_fail.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_fail.setObjectName("btn_fail")
        self.btn.addWidget(self.btn_fail)
        self.btn_pass = QtWidgets.QPushButton(PopUp)
        self.btn_pass.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_pass.setObjectName("btn_pass")
        self.btn.addWidget(self.btn_pass)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btn.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.btn)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(PopUp)
        QtCore.QMetaObject.connectSlotsByName(PopUp)

    def retranslateUi(self, PopUp):
        _translate = QtCore.QCoreApplication.translate
        PopUp.setWindowTitle(_translate("PopUp", "PopUp"))
        self.label_message.setText(_translate("PopUp", "Message"))
        self.label_mnv.setText(_translate("PopUp", "Mã Nhân Viên:"))
        self.btn_fail.setText(_translate("PopUp", "Fail"))
        self.btn_pass.setText(_translate("PopUp", "Pass"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopUp = QtWidgets.QWidget()
    ui = Ui_PopUp()
    ui.setupUi(PopUp)
    PopUp.show()
    sys.exit(app.exec_())
